services:
  - type: web
    name: tiki-resto-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && node --max-old-space-size=512 dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://tikilyon.fr
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
    autoDeploy: true 