services:
  - type: web
    name: tiki-resto-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node --max-old-space-size=512 dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://tikilyon.vercel.app
    autoDeploy: true 